version: "3.9"
services:
  env:
    build: .
    platform: linux/amd64
    volumes:
      - .:/vagrant
    environment:
      - DISPLAY=host.docker.internal:0
    stdin_open: true # docker run -i
    tty: true        # docker run -t

